// alert("Coucous !");                                   Exercice JS13 intégrer du Javascript dans une page web
// console.log("Ah que Coucou !");                         DOM (doucment object model )
// document.write("Coucou beuh !");

// alert("<p>Exemple</p>");

// document.write("<h1>Javascript</h1>")
// const h1 = document.getElementById('myId');
// h1.innerText = 'Javascript, web!';
// console.log(myId);

