
//  //Exercice                            JS 12: les objets natifs 
// let somme = 0
// let count = 0
// let tableau = []
// while (true) {                                   //boucle while
//     let n = parseFloat(window.prompt ("Entrez une valeur numérique("+(count+1) + "/saisie stop à 0):"));
  
//     if (isNaN(n) || n ===0) {
//         break;
//     }
//     tableau.push(n);
//     somme += n;
//     count++;
// }

// if (count> 0){
//     console.log ( "saisie " + count + "valeur(s):");
//     console.log(tablaeu);
//     console.log("somme:" + somme);
//     console.log("moyenne :"+ (somme/count));
// } else{
//     console.log("Aucune valeur n'a été saisie.");
// }

